"""empty message

Revision ID: 1be2acec8c8b
Revises: 363f0b7bd97a
Create Date: 2024-05-09 14:28:13.933307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1be2acec8c8b"
down_revision: Union[str, None] = "363f0b7bd97a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("country", sa.String(), nullable=True))
    op.add_column("account", sa.Column("city", sa.String(), nullable=True))
    op.alter_column(
        "account", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("account", "city")
    op.drop_column("account", "country")
    # ### end Alembic commands ###
